[package]
name = "fast-git-prompt"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19.0"
serde_json = "1.0.122"
serde = { version = "1.0.205", features = ["derive"] }
regex = "1.10.6"
schemars = "0.8.21"
